<a href="https://colab.research.google.com/gist/KKB48/4a00882c18dc7b7b1e3aa9a009af1813/data-processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Loading dataset

The data for this project was obtained by scraping tweets on Twitter posted from January 1, 2016 to December 31, 2022 with the keywords <b>"gabriela"</b> and <b>"npa‚Äù</b>.

In [ ]:
!pip install gdown
!gdown --id 1kLd3Y-M3Q0Tcr73KYx1hs4M_4Y4aIBLR --output dataset.csv
!gdown --id 1vuSNSUZgCQLgCN8BVmZzcqLCSgIniug1 --output stopwords.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (4.6.6)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown) (3.12.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown) (2.27.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from gdown) (1.16.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown) (4.65.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown) (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown) (2.4.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.7.1)
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1kLd3Y-M3Q0Tcr73KYx1hs4M_4Y4aIBLR
To: /content/dataset.csv
100% 238k/238k [00:00<00:00, 94.9MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1vuSNSUZgCQLgCN8BVmZzcqLCSgIniug1
To: /content/stopwords.txt
100% 924/924 [00:00<00:00, 5.35MB/s]

In [ ]:
import pandas as pd

df = pd.read_csv('/content/dataset.csv', header= 0, encoding= 'unicode_escape', index_col='ID')

def deleteSpaces(x):
  return x.title().replace(" ", "")

df = df.rename(columns=deleteSpaces)

print("Raw Dataset:")
df.head(3)

Raw Dataset:

,Timestamp,TweetUrl,Group,Collector,Category,Topic,Keywords,AccountHandle,AccountName,AccountBio,...,QuoteTweets,Views,Rating,Reasoning,Remarks,AddColumnsHere,AddColumnsHere.1,AddColumnsHere.2,Reviewer,Review
ID,,,,,,,,,,,,,,,,,,,,,
42-1,21/03/23 03:57:30,https://twitter.com/Samuel54003886/status/1599...,42.0,"Malimban, Janilyn",REDT,Gabriela partylist is a front of the terrorist...,gabriela npa,@Samuel54003886,Samuel,"""I hate when people confuse EDUCATION & INTELL...",...,1.0,NaN,NaN,The first part of the tweet is about Ka Lelay'...,This tweet has a youtube link which redirects ...,NaN,NaN,NaN,NaN,NaN
42-2,22/03/23 04:51:58,https://twitter.com/ANGBAYANKO3/status/1599321...,42.0,"Malimban, Janilyn",REDT,Gabriela partylist is a front of the terrorist...,gabriela npa,@ANGBAYANKO3,ANG BAYAN KO,tunay na makabayan ay lumalaban sa mapanlinlang,...,0.0,NaN,NaN,There is a lack of sufficient evidence that li...,This tweet is a reply to a conversation,NaN,NaN,NaN,NaN,NaN
42-3,21/03/23 06:29:18,https://twitter.com/ka_npa/status/159722015498...,42.0,"Malimban, Janilyn",REDT,Gabriela partylist is a front of the terrorist...,gabriela npa,@ka_npa,NPA KA,"JOMA, the founding father",...,0.0,NaN,NaN,There is a lack of sufficient evidence that li...,This tweet is a reply to a conversation,NaN,NaN,NaN,NaN,NaN

### Cleaning the data

There are currently <i>956 rows</i> in the dataset but only 150 samples to work with for this project. The raw dataset contains <i>34 columns</i> provided by the scraper used in this project. Note that the columns were altered to have no spaces in between the words using the `deleteSpaces` function and the `rename` function.

We continue cleaning the dataset by extracting the data from relevant columns

In [ ]:
# Extracts the relevant columns
col = ['AccountHandle', 'AccountType', 'Joined',
      'Following', 'Followers', 'Tweet', 
      'TweetType', 'DatePosted', 'ContentType',
      'Likes', 'Replies', 'Retweets', 'QuoteTweets']
df = df[col]

print("Filtered dataset:")
df.head(3)

Filtered dataset:

,AccountHandle,AccountType,Joined,Following,Followers,Tweet,TweetType,DatePosted,ContentType,Likes,Replies,Retweets,QuoteTweets
ID,,,,,,,,,,,,,
42-1,@Samuel54003886,Anonymous,02/22,939.0,523.0,"""Ang paniniwalang magiging mapait ang pagsuko ...","Text, Image, URL",05/12/22 15:14,Rational,3.0,0.0,1.0,1.0
42-2,@ANGBAYANKO3,Anonymous,10/22,45.0,46.0,@RDA47338427 @GilbertM102405 @binimarcia @chie...,"Text, Image, Reply",04/12/22 16:36,Emotional,2.0,0.0,1.0,0.0
42-3,@ka_npa,Anonymous,10/22,21.0,7.0,@NNARAYouth Makibaka para matigil ang TERRORIS...,"Text, Reply",28/11/22 21:25,Emotional,0.0,0.0,0.0,0.0

<br>Then, we check the dataset if there are any empty rows by checking the tail-end of the dataset using `tail`. In our dataset, we can see that there are indeed empty rows.

In [ ]:
# checks if there are empty rows
df.tail(3)

,AccountHandle,AccountType,Joined,Following,Followers,Tweet,TweetType,DatePosted,ContentType,Likes,Replies,Retweets,QuoteTweets
ID,,,,,,,,,,,,,
00-953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<br>Since there are empty rows in our dataset, we drop these rows using the `dropna` function.

In [ ]:
# Drop empty rows
df = df.dropna(how='all')

# Check shape
print("Dataset shape:")
df.shape

Dataset shape:

(150, 13)

 After this, the dataset is left with <i>150 rows and 13 columns</i>, which we were able to determine using the `shape` function.

 The relevant columns in our dataset are as follows:


1.   **AccountHandle** - username of the account
2.   **AccountType** - may only be anonymous, identified, and media
3. **Joined** - date at which the Twitter account was created
4. **Following** - number of users followed by the account
5. **Followers** - number of followers of the account
6. **Tweet** - any message posted to Twitter which may contain photos, videos, links, and text
7. **TweetType** - may be any combination of Text, Image, URL, and Reply
8. **DatePosted** - date at which the tweet was posted which would only be from January 1, 2016 to December 31, 2022
9. **ContentType**: may only be Emotional, Rational, and Transactional
10. **Likes** - number of likes obtained by the tweet
11. **Replies** - number of replies obtained by the tweet
12. **Retweets** -number of retweets obtained by the tweet
13. **QuoteTweets** - number of quote tweets obtained by the tweet
 
 The types of data present from this dataset are the following:

- **Categorical (Qualitative)**: AccountHandle, AccountType, Tweet, TweetType, ContentType
- **Numerical (Quantitative)**: Following, Followers, Likes, Replies, Retweets, QuoteTweets
- **Date**: DatePosted, Joined

### Checking for missing values

We checked for columns with either missing, `None`, or `numpy.NaN` values in the data frame columns using the `.isna().any()` function. From here, we can see the columns from the dataset in which we need to handle missing values if there are any. If none, (i.e. the `isna()` function will return nothing) then we proceed with transforming the data.

From our dataset, we can see that there are no columns with any missing values.

In [ ]:
# Find columns with missing values
print("Columns with missing/nan values:")
col_with_na = df.columns[df.isna().any()]

if len(col_with_na) == 0:
  print("None")
else:
  for col in col_with_na:
    print(col, df[col].isna().sum(), sep=": ")

Columns with missing/nan values:
None

### Transforming data

Given the three categories of features within the data set (categorical, numerical, and date), we transformed the data within the categories to similar data type in order to remain consistency and ensure uniformity of data types across the dataset. For categorical values, we changed the data into a **string (str)** datatype while numerical values are transformed into **64-bit signed integer** data type. 

Meanwhile for the data category, the Joined column uses the `to_period(‚Äôm‚Äô)` function in order to cast the datetimelike value and cast it to index at a monthly frequency. On the other hand, the DatePosted column will be transformed to use the default datetime format which is `YYYY-MM-DD HH:MM:SS`.

In [ ]:
feat_cat = ['AccountHandle', 'AccountType', 'Tweet', 'TweetType', 'ContentType']
feat_num = ['Following', 'Followers', 'Likes', 'Replies', 'Retweets', 'QuoteTweets']
feat_date = ['DatePosted', 'Joined']

In [ ]:
import numpy as np

print("Feature data types:")
print(df.dtypes)

print('\nTransforming categorical features...')
for col in feat_cat:
    df[col] = df[col].astype('str')

print('Transforming numerical features...')
for col in feat_num:
    df[col] = df[col].astype(np.int64)
    
df['Joined'] = pd.to_datetime(df['Joined'], format='%m/%y').dt.to_period('m')
df['DatePosted'] = pd.to_datetime(df['DatePosted'])

print('\nFeature data types (converted):')
print(df.dtypes)

Feature data types:
AccountHandle     object
AccountType       object
Joined            object
Following        float64
Followers        float64
Tweet             object
TweetType         object
DatePosted        object
ContentType       object
Likes            float64
Replies          float64
Retweets         float64
QuoteTweets      float64
dtype: object

Transforming categorical features...
Transforming numerical features...

Feature data types (converted):
AccountHandle            object
AccountType              object
Joined                period[M]
Following                 int64
Followers                 int64
Tweet                    object
TweetType                object
DatePosted       datetime64[ns]
ContentType              object
Likes                     int64
Replies                   int64
Retweets                  int64
QuoteTweets               int64
dtype: object

In [ ]:
print('Categorical features summary:')
df[feat_cat].describe()

Categorical features summary:

,AccountHandle,AccountType,Tweet,TweetType,ContentType
count,150,150,150,150,150
unique,120,3,150,15,2
top,@shiningtwicexo,Anonymous,"""Ang paniniwalang magiging mapait ang pagsuko ...","Text, Reply",Rational
freq,13,93,1,82,75

In [ ]:
print('Numerical features summary:')
df[feat_num].describe(datetime_is_numeric=True)

Numerical features summary:

,Following,Followers,Likes,Replies,Retweets,QuoteTweets
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,998.426667,4101.326667,11.706667,0.973333,3.726667,0.480000
std,1604.030194,19978.229326,62.870331,5.656791,20.213258,3.304908
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.500000,30.000000,0.000000,0.000000,0.000000,0.000000
50%,259.000000,272.500000,1.000000,0.000000,0.000000,0.000000
75%,1234.000000,1371.250000,3.000000,0.000000,1.000000,0.000000
max,9384.000000,204589.000000,701.000000,66.000000,198.000000,39.000000

### Categorical Encoding

To simplify the categorical features in the dataset, we employ categorical encoding for the AccountType, ContentType, and TweetType features. Thus, we encoded these features into their respective numerical values.

For **AccountType**, the encoding was:

- 0 for ‚ÄúAnonymous‚Äù
- 1 for ‚ÄúIdentified‚Äù
- 2 for ‚ÄúMedia‚Äù

and the encoded value was saved as `Temp_AccountType` feature in the `df` dataset.

For **ContentType**, the encoding was:

- 0 for ‚ÄúEmotional‚Äù
- 1 for ‚ÄúRational‚Äù, and
- 2 for ‚ÄúTransactional‚Äù

and the encoded value is saved as `Temp_ContentType` feature in the `df` dataset.

For the TweetType, we split the string of the feature to tokenize the content of the column into a list. Then, we mapped the list of tokens of the TweetType column via <i>one hot encoding</i> to see if the tweet contains certain tweet_types (Text, Image, URL, and Reply) by putting a value of 1 to their respective feature under the `df` dataset.

In [ ]:
from sklearn import preprocessing

encoder_account_type =  preprocessing.LabelEncoder().fit(df['AccountType'])
df['Temp_AccountType'] = encoder_account_type.transform(df['AccountType'])

encoder_content_type =  preprocessing.LabelEncoder().fit(df['ContentType'])
df['Temp_ContentType'] = encoder_content_type.transform(df['ContentType'])

In [ ]:
# Onehot encoding for TweetType
def tweet_type_split(x):
  return x.split(', ')

def tweet_type_classification(tweettype, x):
  if tweettype in x:
    return 1
  return 0

df['TweetType'] = df['TweetType'].apply(tweet_type_split)

tweet_types = ['Text', 'Image', 'URL', 'Reply']
for tweet_type in tweet_types:
  df[f'Temp_TweetType{tweet_type}'] = df['TweetType'].apply(lambda x: tweet_type_classification(tweet_type, x))

In [ ]:
df.head(3)

,AccountHandle,AccountType,Joined,Following,Followers,Tweet,TweetType,DatePosted,ContentType,Likes,Replies,Retweets,QuoteTweets,Temp_AccountType,Temp_ContentType,Temp_TweetTypeText,Temp_TweetTypeImage,Temp_TweetTypeURL,Temp_TweetTypeReply
ID,,,,,,,,,,,,,,,,,,,
42-1,@Samuel54003886,Anonymous,2022-02,939,523,"""Ang paniniwalang magiging mapait ang pagsuko ...","[Text, Image, URL]",2022-05-12 15:14:00,Rational,3,0,1,1,0,1,1,1,1,0
42-2,@ANGBAYANKO3,Anonymous,2022-10,45,46,@RDA47338427 @GilbertM102405 @binimarcia @chie...,"[Text, Image, Reply]",2022-04-12 16:36:00,Emotional,2,0,1,0,0,0,1,1,0,1
42-3,@ka_npa,Anonymous,2022-10,21,7,@NNARAYouth Makibaka para matigil ang TERRORIS...,"[Text, Reply]",2022-11-28 21:25:00,Emotional,0,0,0,0,0,0,1,0,0,1

### Normalization

In order to ensure uniformity in how data looks, reads, and can be utilized for machine learning modeling (ML modeling), we normalized the features with numerical values as described in the `feat_num` of df dataset. We used the `MinMaxScaler()` function of preprocessing module from sklearn to scale the features from the interval <i>[0,1]</i>. We first fit the scaler using the `fit()` function to estimate the minimum and maximum observable values. Then, we normalized the data using the `transform()` function. The normalized data is now stored in **df_scaled**.

In [ ]:
def rename_cols(x):
  return f'Temp_{x}'

scaler = preprocessing.MinMaxScaler()
scaler_temp = scaler.fit(df[feat_num])

df_scaled = df[feat_num].copy(deep=True)
df_scaled[feat_num] = scaler_temp.transform(df[feat_num])
df_scaled.rename(columns=rename_cols, inplace=True)
df_scaled.describe().style

In [ ]:
df = df.join(df_scaled)
df.head(3)

,AccountHandle,AccountType,Joined,Following,Followers,Tweet,TweetType,DatePosted,ContentType,Likes,...,Temp_TweetTypeText,Temp_TweetTypeImage,Temp_TweetTypeURL,Temp_TweetTypeReply,Temp_Following,Temp_Followers,Temp_Likes,Temp_Replies,Temp_Retweets,Temp_QuoteTweets
ID,,,,,,,,,,,,,,,,,,,,,
42-1,@Samuel54003886,Anonymous,2022-02,939,523,"""Ang paniniwalang magiging mapait ang pagsuko ...","[Text, Image, URL]",2022-05-12 15:14:00,Rational,3,...,1,1,1,0,0.099872,0.002556,0.004280,0.0,0.005051,0.025641
42-2,@ANGBAYANKO3,Anonymous,2022-10,45,46,@RDA47338427 @GilbertM102405 @binimarcia @chie...,"[Text, Image, Reply]",2022-04-12 16:36:00,Emotional,2,...,1,1,0,1,0.004583,0.000225,0.002853,0.0,0.005051,0.000000
42-3,@ka_npa,Anonymous,2022-10,21,7,@NNARAYouth Makibaka para matigil ang TERRORIS...,"[Text, Reply]",2022-11-28 21:25:00,Emotional,0,...,1,0,0,1,0.002025,0.000034,0.000000,0.0,0.000000,0.000000

###Binning Date Features

In order to organize the continuous date and time data, it was divided into either **Monthly** or **Yearly** bins or intervals. 

For the **DatePosted** Feature, the datetime data type is converted into periods using the `to_period(‚Äôm‚Äô)` function. Hence, the DatePosted feature now contains the month when the tweet was posted. Then, the column was divided into monthly interval bins by using `post_bins = pd.period_range(post_start, post_end, freq='M')` where `post_start` is the earliest DatePosted month into the dataset while the `post_end` is the latest and the `freq` or frequency is set to **‚ÄòM‚Äô** or **monthly**. Thus, the post_bins contains the binning of the DatePosted feature returned by the period_range function which returns a fixed monthly frequency PeriodIndex.

The JoinedDate feature is converted into yearly interval using the `PeriodIndex(df[‚ÄôJoined‚Äô]).year`. Thus, the added temporary feature in the dataset **Temp_YearJoined** now contains the year when the account was created in twitter.

In [ ]:
# Binning DatePosted feature into months
df['Temp_MonthPosted'] = pd.to_datetime(df['DatePosted']).dt.to_period('m').astype('str')

post_start = df['Temp_MonthPosted'].min()
post_end = df['Temp_MonthPosted'].max()

post_bins = pd.period_range(post_start, post_end, freq='M')

# Binning JoinedDate into years
df['Temp_YearJoined'] = pd.PeriodIndex(df['Joined']).year

In [ ]:
df.head(3)

,AccountHandle,AccountType,Joined,Following,Followers,Tweet,TweetType,DatePosted,ContentType,Likes,...,Temp_TweetTypeURL,Temp_TweetTypeReply,Temp_Following,Temp_Followers,Temp_Likes,Temp_Replies,Temp_Retweets,Temp_QuoteTweets,Temp_MonthPosted,Temp_YearJoined
ID,,,,,,,,,,,,,,,,,,,,,
42-1,@Samuel54003886,Anonymous,2022-02,939,523,"""Ang paniniwalang magiging mapait ang pagsuko ...","[Text, Image, URL]",2022-05-12 15:14:00,Rational,3,...,1,0,0.099872,0.002556,0.004280,0.0,0.005051,0.025641,2022-05,2022
42-2,@ANGBAYANKO3,Anonymous,2022-10,45,46,@RDA47338427 @GilbertM102405 @binimarcia @chie...,"[Text, Image, Reply]",2022-04-12 16:36:00,Emotional,2,...,0,1,0.004583,0.000225,0.002853,0.0,0.005051,0.000000,2022-04,2022
42-3,@ka_npa,Anonymous,2022-10,21,7,@NNARAYouth Makibaka para matigil ang TERRORIS...,"[Text, Reply]",2022-11-28 21:25:00,Emotional,0,...,0,1,0.002025,0.000034,0.000000,0.0,0.000000,0.000000,2022-11,2022

### Interpolation

  To aggregate and interpolate the data, we first created an empty df dataset named `df_time_series` in which the features and rows are characterized with:
  - First feature is the total count of tweets per time bin
  - The succeeding features are each type of content and account separated by each column, and
  - The rows are the indices of the time binning with monthly frequency

  Then, the `count_time_series` function counts the number of tweets for each column depending on the content of the tweet and account type of the user of the tweet. Note that there will be null values in `df_time_series` since the values of the columns in `df_time_series` will only increase if it is encountered in the dataset.

  Then, we interpolated the `df_time_series` using the interpolate function with **linear** method. Moreover, in order to remove the leading NaN values in the dataset, we filled the values with 0 using `fillna(0)` method.

In [ ]:
# CHANGED

import numpy as np

ContentType = ['ContentType_Rational', 'ContentType_Emotional', 'ContentType_Transactional']
AccountType = ['AccountType_Anonymous', 'AccountType_Identified', 'AccountType_Media']

df_time_series = pd.DataFrame(columns=['TotalCount']+ContentType+AccountType, index=post_bins)
df_time_series.index.name="MonthPosted"

for col in df_time_series.columns:
    df_time_series[col] = df_time_series[col].astype(float)

def count_time_series(x,df_op):
  content = encoder_content_type.inverse_transform([x['Temp_ContentType']])[0]
  account = encoder_account_type.inverse_transform([x['Temp_AccountType']])[0]
  if np.isnan(df_op['TotalCount'].loc[x['Temp_MonthPosted']])==True:
    df_op['TotalCount'].loc[x['Temp_MonthPosted']]=0
  if np.isnan(df_op[f'ContentType_{content}'].loc[x['Temp_MonthPosted']])==True:
    df_op[f'ContentType_{content}'].loc[x['Temp_MonthPosted']]=0
  if np.isnan(df_op[f'AccountType_{account}'].loc[x['Temp_MonthPosted']])==True:
    df_op[f'AccountType_{account}'].loc[x['Temp_MonthPosted']]=0

  df_op['TotalCount'].loc[x['Temp_MonthPosted']] = df_op[f'TotalCount'].loc[x['Temp_MonthPosted']] +1
  df_op[f'ContentType_{content}'].loc[x['Temp_MonthPosted']] = df_op[f'ContentType_{content}'].loc[x['Temp_MonthPosted']] +1
  df_op[f'AccountType_{account}'].loc[x['Temp_MonthPosted']] = df_op[f'AccountType_{account}'].loc[x['Temp_MonthPosted']] +1
      
df.apply(lambda x: count_time_series(x,df_time_series), axis=1)

df_time_series = df_time_series.interpolate(method='linear').fillna(0)
df_time_series

,TotalCount,ContentType_Rational,ContentType_Emotional,ContentType_Transactional,AccountType_Anonymous,AccountType_Identified,AccountType_Media
MonthPosted,,,,,,,
2018-09,1.000000,1.000000,0.000000,0.0,0.00,1.000000,0.00
2018-10,1.000000,1.000000,0.000000,0.0,0.00,1.000000,0.00
2018-11,1.000000,1.000000,0.000000,0.0,0.00,1.000000,0.00
2018-12,1.000000,1.000000,0.000000,0.0,0.00,1.000000,0.00
2019-01,1.000000,1.000000,0.000000,0.0,0.00,1.000000,0.00
2019-02,1.000000,1.000000,0.000000,0.0,0.00,1.000000,0.00
2019-03,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-04,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-05,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-06,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-07,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-08,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-09,1.000000,1.000000,1.000000,0.0,1.00,1.000000,0.00
2019-10,1.000000,1.000000,1.000000,0.0,1.00,1.222222,0.00
2019-11,1.000000,1.000000,1.000000,0.0,1.00,1.444444,0.00
2019-12,1.000000,1.000000,1.000000,0.0,1.00,1.666667,0.00
2020-01,1.000000,1.000000,1.000000,0.0,1.00,1.888889,0.00
2020-02,1.000000,1.000000,1.000000,0.0,1.25,2.111111,1.00
2020-03,1.333333,1.000000,1.000000,0.0,1.50,2.333333,1.00
2020-04,1.666667,1.000000,1.000000,0.0,1.75,2.555556,1.00
2020-05,2.000000,1.000000,1.000000,0.0,2.00,2.777778,1.00
2020-06,6.000000,1.000000,5.000000,0.0,3.00,3.000000,1.00
2020-07,1.000000,1.000000,3.666667,0.0,1.00,2.333333,1.00
2020-08,1.000000,6.333333,2.333333,0.0,8.00,1.666667,1.00
2020-09,1.000000,11.666667,1.000000,0.0,15.00,1.000000,1.00
2020-10,31.000000,17.000000,14.000000,0.0,22.00,9.000000,1.00
2020-11,2.000000,1.000000,1.000000,0.0,1.00,1.000000,1.00
2020-12,2.000000,1.000000,1.000000,0.0,2.00,1.000000,1.00
2021-01,1.500000,1.000000,1.500000,0.0,1.50,1.000000,1.00
2021-02,1.000000,1.000000,2.000000,0.0,1.00,1.000000,1.00
2021-03,1.000000,1.000000,2.500000,0.0,1.00,1.000000,1.00
2021-04,3.000000,1.200000,3.000000,0.0,1.00,2.000000,1.00
2021-05,3.000000,1.400000,3.000000,0.0,1.00,2.000000,1.00
2021-06,2.000000,1.600000,2.000000,0.0,1.00,2.000000,1.00
2021-07,1.000000,1.800000,1.000000,0.0,1.00,2.000000,1.00
2021-08,3.000000,2.000000,1.000000,0.0,1.00,2.000000,1.00
2021-09,2.000000,2.000000,2.000000,0.0,1.50,2.000000,1.00
2021-10,5.000000,2.000000,3.000000,0.0,2.00,3.000000,1.00
2021-11,1.000000,1.500000,1.000000,0.0,1.50,1.000000,1.00
2021-12,2.000000,1.000000,1.000000,0.0,1.00,1.000000,1.00
2022-01,7.000000,2.000000,5.000000,0.0,4.00,3.000000,1.00
2022-02,3.000000,2.000000,1.000000,0.0,3.00,3.000000,1.00
2022-03,12.000000,8.000000,4.000000,0.0,9.00,3.000000,1.00
2022-04,8.000000,4.000000,4.000000,0.0,7.00,1.000000,1.00
2022-05,12.000000,4.000000,8.000000,0.0,8.00,3.000000,1.00
2022-06,6.000000,4.000000,2.000000,0.0,2.00,3.000000,1.00
2022-07,6.000000,4.000000,2.000000,0.0,4.00,2.000000,1.25
2022-08,7.000000,5.000000,2.000000,0.0,4.00,3.000000,1.50
2022-09,5.000000,2.000000,3.000000,0.0,3.00,2.000000,1.75
2022-10,7.000000,5.000000,2.000000,0.0,4.00,1.000000,2.00
2022-11,2.000000,1.000000,1.000000,0.0,2.00,1.000000,2.00
2022-12,2.000000,1.000000,2.000000,0.0,2.00,1.000000,2.00

In [ ]:
print(df.dtypes)

AccountHandle                  object
AccountType                    object
Joined                      period[M]
Following                       int64
Followers                       int64
Tweet                          object
TweetType                      object
DatePosted             datetime64[ns]
ContentType                    object
Likes                           int64
Replies                         int64
Retweets                        int64
QuoteTweets                     int64
Temp_AccountType                int64
Temp_ContentType                int64
Temp_TweetTypeText              int64
Temp_TweetTypeImage             int64
Temp_TweetTypeURL               int64
Temp_TweetTypeReply             int64
Temp_Following                float64
Temp_Followers                float64
Temp_Likes                    float64
Temp_Replies                  float64
Temp_Retweets                 float64
Temp_QuoteTweets              float64
Temp_MonthPosted               object
Temp_YearJoined                 int64
dtype: object

### Natural Language Processing

In order to obtain a proper analysis of the tweets in our dataset, the removal of stop words, links, mentions, hashtags, and some punctuations in the tweets were performed on the contents of each tweet.

These removals are necessary in order to keep the focus on key points of the tweets.

In [ ]:
# Remove stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
import string

stop_words = stopwords.words('english')
f=open('/content/stopwords.txt')
filipino_stopwords = f.read().splitlines()
stop_words+=filipino_stopwords+[*string.punctuation]

df['Tweet_stop'] = df['Tweet'].str.lower()
df['Tweet_stop'] = df['Tweet_stop'].apply(lambda words: ' '.join(word for word in words.split() if word not in stop_words))
df.head(3).style

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
# removes links, mentions, hashtags, and some punctuations in the tweets
import re

def text_extract(tweet):
    http_link = re.sub(r'\shttp\S*', '', tweet)
    com_link = re.sub(r'\s\S+.com\S*', '', http_link)
    mentions = re.sub(r'@\S+\s*','',com_link)
    alt_text = re.sub("[\{].*?[\}]", "", mentions)
    hashtags = re.sub(r'#\S+\s*','',alt_text)
    return hashtags

def nreplace(tweet):
    return tweet.replace('\n',' ')

def lowercase(tweet):
    return tweet.lower()
punctuations = ''.join(['!', '"', '#', '$', '%',  "'", '(', ')', '*', '+', ',', '.', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~'])
df['Tweet_stop'] = df['Tweet_stop'].map(text_extract).map(nreplace).map(lowercase).apply(lambda words: words.translate(str.maketrans('', '', punctuations)))
df[['Tweet','Tweet_stop']].head(5)

,Tweet,Tweet_stop
ID,,
42-1,"""Ang paniniwalang magiging mapait ang pagsuko ...",ang paniniwalang magiging mapait pagsuko rebel...
42-2,@RDA47338427 @GilbertM102405 @binimarcia @chie...,msy sayo redbtagging si badoy rrd tagging pags...
42-3,@NNARAYouth Makibaka para matigil ang TERRORIS...,makibaka matigil terroristang cpp npa ndf urba...
42-4,Arlene Brosas ng Gabriela. Isa sa mataas na li...,arlene brosas gabriela mataas lider cpp npa ti...
42-5,Nakabaon sa mga sangay ng ating gobyerno ang m...,nakabaon sangay gobyerno npa congress senate l...

After removing the unnecessary parts of the tweets, we proceed with obtaining the top 10 most frequent words used in the tweets.

In [ ]:
# Count word frequency
print("Most commonly used words in tweets:")
word_freq = df['Tweet_stop'].str.lower().str.split().explode().value_counts()
word_freq[:10].to_frame().style

Most commonly used words in tweets:

### Visualization

In order to gain deeper insights from the dataset that we have, we created multiple visualizations that helped us to better understand the underlying patterns and trends that were not immediately apparent from the raw data.

To break down the distribution of tweets with disinformation based on account type and content type, we made pie charts that display the overall percentage of tweets for each account type and content type.

From the pie chart on the left we can see that anonymous users post the most amount of tweets containing mis/disinformation about the topic.

Meanwhile, the pie chart on the right shows how tweets containing mis/disinformation are split evenly between having rational and emotional content.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import plotly.graph_objects as go

palette_color = sns.color_palette('Set2')

In [ ]:
fig = make_subplots(rows=1, cols=2)

fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]])

accounts = df.groupby(['Temp_AccountType'])['Temp_AccountType'].count()
fig.add_trace(
    go.Pie(
      labels=encoder_account_type.inverse_transform(accounts.index), 
      values=accounts.values, 
      textinfo='label+percent', 
      name="Account types", title="Account Types",
      ),
    1, 1)

contents = df.groupby(['Temp_ContentType'])['Temp_ContentType'].count()
fig.add_trace(
    go.Pie(
        labels=encoder_content_type.inverse_transform(contents.index), 
        values=contents.values, 
        textinfo='label+percent', 
        name="Content types", 
        title="Content types",
        ),
      1, 2)

fig.update_traces(hole=.4, hoverinfo="label+value+name")

fig.update_layout(
    title_text="Tweets with disinformation",
    showlegend=False,
    autosize=False,
    width=960,
    height=540,
    )
fig.show()

<br>To analyze the content type of the tweets made by the different types of accounts, we created a bar graph that shows the most frequent content type among the different account types.

For tweets posted by anonymous accounts, we can see how the there is no apparent significant difference between the number of tweets containing rational and emotional content.

For tweets posted by identified accounts, we can see that there are more tweets that contain emotional content.

For tweets posted by media accounts, we can see that there are only tweets that contain rational content.

In [ ]:
temp_cont_types = df['Temp_ContentType'].unique()

fig = go.Figure()
for cont_type in temp_cont_types:
  y = df[df['Temp_ContentType']==cont_type].groupby(['Temp_AccountType'])['Temp_AccountType'].count()
  fig.add_trace(
      go.Bar(
        x=encoder_account_type.inverse_transform(y.index), 
        y=y.values, 
        name = encoder_content_type.inverse_transform([cont_type])[0]
      )
  )

fig.update_layout(
    barmode='group', 
    xaxis={'categoryorder':'total descending'}, 
    title="Account Type - Content Type Distribution",
    autosize=False,
    width=960,
    height=540,
    )
fig.show()

<br>To analyze the time posted for the tweets, we created a bar graph that shows the most frequent month that the tweets were posted by the users.

Here, we can see that October was the most frequent month that the tweets were posted by the users.

In [ ]:
# CHANGED

fig = go.Figure(
    go.Bar(
        x=df_time_series.index.astype(str), 
        y=df_time_series['TotalCount'], 
        name = encoder_content_type.inverse_transform([cont_type])[0]
      )
)
fig.update_layout(
    xaxis={'categoryorder':'total descending'}, 
    title="Frequency of tweets with disinformation",
    autosize=False,
    width=960,
    height=540,
    )
fig

<br>To analyze the time at which different accounts post tweets, we created a line plot that shows the most frequent month in which each account type posted their tweets.

Here, we can see that for all account types, October is the most frequent month in which the tweets were posted.

In [ ]:
# CHANGED

temp_acc_types = df['Temp_AccountType'].unique()

fig = go.Figure()
for acc_type in temp_acc_types:
  y = df_time_series[f'AccountType_{encoder_account_type.inverse_transform([acc_type])[0]}']
  
  fig.add_trace(
      go.Scatter(
        x=y.index.astype(str), 
        y=y.values, 
        name = encoder_account_type.inverse_transform([acc_type])[0]
      )
  )

fig.update_layout(
    xaxis={'categoryorder':'total descending'}, 
    title="Account Type - Month Posted",
    autosize=False,
    width=960,
    height=540,
    )
fig.show()

<br>To analyze the time at which tweets with different content types were posted, we created a line plot that shows the most frequent month in which tweets with each content type were posted.

Here, we can see that for both content types, October is the most frequent month in which tweets were posted.

In [ ]:
# CHANGED

temp_cont_types = df['Temp_ContentType'].unique()

fig = go.Figure()
for cont_type in temp_cont_types:
  y = df_time_series[f'ContentType_{encoder_content_type.inverse_transform([cont_type])[0]}']
  
  fig.add_trace(
      go.Scatter(
        x=y.index.astype(str), 
        y=y.values, 
        name = encoder_content_type.inverse_transform([cont_type])[0]
      )
  )


fig.update_layout(
    barmode='stack', 
    xaxis={'categoryorder':'total descending'}, 
    title="Content type - Month Posted",
    autosize=False,
    width=960,
    height=540,
    )
fig.show()

<br>To analyze the time at which the accounts were created, we made a bar graph that shows the most frequent year in which the accounts were created.

Here, we can see that 2020 was the most frequent year in which the accounts were created.

In [ ]:
df_account_details = df[['AccountHandle', 'Temp_AccountType', 'Temp_YearJoined']].copy(deep=True)
df_account_details.drop_duplicates(subset='AccountHandle', keep='first', inplace=True) 

fig = px.histogram(
    df_account_details, 
    x="Temp_YearJoined", 
    title="Frequency of account handles that joined per year",
    width=960,
    height=540,
    )
fig.show()

<br>To analyze the time at which different types of accounts were created, we made a bar graph that shows the most frequent year in which each account type was created.

Here, we can see that 2020 was the most frequent year in which the accounts were created, wherein anonymous accounts were the most frequent type of account created.

In [ ]:
temp_acc_types = df['Temp_AccountType'].unique()
fig = go.Figure()
print(temp_acc_types)
for acc_type in temp_acc_types:
  y = df_account_details[df_account_details['Temp_AccountType']==acc_type].groupby(['Temp_YearJoined'])['Temp_YearJoined'].count()
  fig.add_trace(
      go.Bar(
        x=y.index, 
        y=y.values, 
        name = encoder_account_type.inverse_transform([acc_type])[0]
      )
  )


fig.update_layout(
    barmode='group', 
    xaxis={'categoryorder':'total descending'}, 
    title="Account type - Year Joined",
    width=960,
    height=540,
    )
fig.show()

[0 1 2]

<br>To analyze the comparison between the time in which the tweets were posted and the time in which their respective accounts were created, we created a heatmap to determine the most frequent pairing of month the tweet was posted and the year when the account was created.

Here, we can see that the column of the year 2020 contains a good number of the saturated cells as well as the most saturated cell, wherein the most saturated cell is the pairing of October time of posting and 2020 year of creation.

In [ ]:
# CHANGED

import numpy as np

join_start = df['Temp_YearJoined'].min()
join_end = df['Temp_YearJoined'].max()

join_bins = [x for x in range(join_start,join_end+1)]
df_posted_vs_joined = pd.DataFrame(columns = post_bins.astype('str'),index=join_bins)

df_posted_vs_joined = df_posted_vs_joined.fillna(0)
def count_joined_posted(x,df_op):
  df_op[x['Temp_MonthPosted']].loc[x['Temp_YearJoined']] = df_op[x['Temp_MonthPosted']].loc[x['Temp_YearJoined']] +1
      
df[['Temp_YearJoined','Temp_MonthPosted']].apply(lambda x: count_joined_posted(x,df_posted_vs_joined), axis=1)
df_posted_vs_joined

MonthPosted,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,...,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12
2008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2009,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,1,0,0
2010,0,0,0,0,0,0,0,0,0,0,...,0,3,4,1,2,1,1,2,1,0
2011,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2012,0,0,0,0,0,0,0,0,1,0,...,1,1,0,0,1,0,0,0,0,0
2013,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2015,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,1,0,0,0,0
2016,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2017,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
2018,0,0,0,0,0,0,0,0,0,0,...,0,2,3,0,0,0,0,0,0,0
2019,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,2,0,1
2021,0,0,0,0,0,0,0,0,0,0,...,4,0,0,2,1,1,2,1,0,0
2022,0,0,0,0,0,0,0,0,0,0,...,1,1,1,2,2,4,2,1,1,1

In [ ]:
# CHANGED

fig = go.Figure(
    data=go.Heatmap(
        x=post_bins.astype('str'),
        y=join_bins,
      z=df_posted_vs_joined)
  )

fig.update_layout(
    width = 1000, 
    height = 400,
    autosize = False )
fig.show()